import "./globals.css";
import StarCanvas from "./Components/Navbar/StarBg";


const poppins_init = Poppins({
  variable: "--font-poppins",
  weight:['100', '300', '700', '900'],
  subsets: ["latin"],
});

export const metadata = {
  title: "Reza Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins_init.className} antialiased`}>
        <StarCanvas/>
        {children}
      </body>
    </html>
  );
}


